name: FRC code tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@master
    - name: 
      uses: actions/setup-python@v1
      with:
        version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest
